### ISSUE TITLE
having issues compiling project

### ISSUE THREAD

**Issue by shattars3d** [NeilNie/Track-Your-Run#3]
Hey,
i am just running your project for fun,but its giving me these errors..

ld: warning: directory not found for option
 '-L/Users//Library/Developer/Xcode/DerivedData/Run-cltmfnuiujcqgwavllkejcboptgz/Build/Products/Debug-iphoneos/FrameAccessor'
ld: warning: directory not found for option
 '-L/Users//Library/Developer/Xcode/DerivedData/Run-cltmfnuiujcqgwavllkejcboptgz/Build/Products/Debug-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option
 '-L/Users//Library/Developer/Xcode/DerivedData/Run-cltmfnuiujcqgwavllkejcboptgz/Build/Products/Debug-iphoneos/MKFoundationKit'
ld: warning: directory not found for option
 '-L/Users//Library/Developer/Xcode/DerivedData/Run-cltmfnuiujcqgwavllkejcboptgz/Build/Products/Debug-iphoneos/UICountingLabel'
ld: library not found for -lFrameAccessor
clang: error: linker command failed with exit code 1 (use -v to see invocation)

also what if I want to run this project without these pods..

**Comment by NeilNie** [comment]
First, make sure the the pods are not missing. Secondly, you have to open the **.xcworkspace(white)** rather than . xcodeproj(blue). You might have to install the pods. Otherwise it will give you pod related issues.

**Comment by NeilNie** [comment]
Thanks for your interest in running my project. :)

**Comment by shattars3d** [comment]
hey,  yeah its a pretty cool project, I'm mostly interesting in the heart rate/workout area.
I am trying to create an iwatch app with a heart rate monitor. Your code has helped a lot!
 
thanks
