### ISSUE TITLE
Run watch issue

### ISSUE THREAD

**Issue by shattars3d** [NeilNie/Track-Your-Run#4]
Hey, when you run Run on the apple watch, none of the data is being sent back to the iPhone. Why is that? everything seem to correct.
You are running wcsession activated, along with the delegates, but no data?..

**Comment by NeilNie** [comment]
Hello, thank you for your comment. I will look into as soon as possible. WatchKit has changed a lot since the last time I updated the project. I will send you a follow up.

**Comment by shattars3d** [comment]
perfect, thanks.. let me know issue, i will help you fix it

**Comment by shattars3d** [comment]
hey, @NeilNie , any updates on the apple watch communication with the iPhone?

**Comment by shattars3d** [comment]
@NeilNie  i have fixed some issues, it looks like the way your sending the watch data is an old way in watch os. Also, they way you retrieve watch data needs to be upgraded. I can send you the code, but your whole project will be needed to upgrade...

**Comment by NeilNie** [comment]
If you have any more questions, comments about the WatchOS issue, please leave a comment below or contact me [directly](mailto:contact@neilnie.com). Thanks!
